### ISSUE TITLE
"Uncaught TypeError: Cannot read property 'prototype' of undefined" when starting inspector

### ISSUE THREAD

**Issue by akinnee** [malroc/backbone-component#6]
Screenshot: http://grab.by/FEuY

I am calling this at the start of my app and it doesn't help:
```
if (window.__agent) {
		window.__agent.disableAnalytics = true;
		window.__agent.start(Backbone, Marionette);
	}
```

**Comment by malroc** [comment]
@akinnee why do you think the issue is related to Backbone.Component? I don't see it in the call stack.

**Comment by akinnee** [comment]
Shoot, I'm sorry. I meant to submit this to Marionette Inspector: https://github.com/marionettejs/marionette.inspector
